Repository COVESA/vehicle_signal_specification, pull requests merged in 2023-11, with the labels that each got.

#684 Update pre-commit config file
  .pre-commit-config.yaml
Labels: Scope:Trivial, Status:Review

#676 Align Temperature Signals
  spec/Powertrain/CombustionEngine.vspec
  spec/Powertrain/ElectricMotor.vspec
  spec/Powertrain/Transmission.vspec
Labels: Scope:Major, Status:Review

#681 added Auto signal
  spec/include/PowerOptimize.vspec
Labels: Status:Review

#691 Fix quantity documentation
  docs-gen/content/rule_set/data_entry/data_units.md
Labels: Scope:Trivial

#693 Fix a typo in the license documentation
  docs-gen/content/license/_index.md
Labels: Scope:Trivial
